package com.collaborativeclouds.mappers;
// Generated Feb 1, 2015 9:38:34 AM by Hibernate Tools 3.6.0



/**
 * Parking generated by hbm2java
 */
public class Parking  implements java.io.Serializable {


     private String slotno;
     private String status;
     private String code;
     private String username;

    public Parking() {
    }

	
    public Parking(String slotno, String status) {
        this.slotno = slotno;
        this.status = status;
    }
    public Parking(String slotno, String status, String code, String username) {
       this.slotno = slotno;
       this.status = status;
       this.code = code;
       this.username = username;
    }
   
    public String getSlotno() {
        return this.slotno;
    }
    
    public void setSlotno(String slotno) {
        this.slotno = slotno;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


